sonar.projectKey=foresight-frontend
sonar.projectName=Foresight Frontend

sonar.sources=frontend/src
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.snap,**/Futuros*.html,**/Futuros*_files/**

sonar.tests=frontend/src/test
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx

sonar.sourceEncoding=UTF-8
sonar.typescript.tsconfigPath=frontend/tsconfig.json
